version: 2.1

orbs:
    # circleci/aws-ecr@6.1.0というorbをaws-ecrというaliasをつけて扱う
    aws-ecr: circleci/aws-ecr@6.1.0
    aws-ecs: circleci/aws-ecs@0.0.8

workflows:
    # build_and_push_imageという名前のworkflowを定義
    build_and_push_image:
        # workflowで実行するjobの順番を定義
        jobs:
        - test # デプロイ操作前にテストを実行
        - aws-ecr/build-and-push-image:
            requires:
                - test # テストに成功したときだけデプロイ操作に移る
            region: AWS_REGION
            account-url: AWS_ECR_ACCOUNT_URL
            repo: 'power-phrase2-api'
            tag: "${CIRCLE_SHA1}"
            dockerfile: docker/api/Dockerfile
            filters:
              branches:
                  only:
                  - master
        - aws-ecs/deploy-service-update:
            requires:
                - aws-ecr/build-and-push-image
            family: 'power-phrase2-api-task'
            cluster-name: 'power-phrase2-api-cluster'
            service-name: 'power-phrase2-api-service'
            container-image-name-updates: 'container=power-phrase2-api-container,tag=${CIRCLE_SHA1}'
            filters:
                branches:
                    only:
                    - master

jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.15.2
        environment:
          SERVER_PORT: 1323
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: power-phrase2-test
          DB_USER: root
          DB_PASSWORD: power-phrase2
          JWT_SIGNING_KEY: secret

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:8.0.21
        environment:
          MYSQL_ROOT_PASSWORD: power-phrase2
          MYSQL_DATABASE: power-phrase2-test
          MYSQL_USER: kazuya
          MYSQL_PASSWORD: kazuya

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/k-kazuya0926/power-phrase2-api
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run:
      # プライマリ コンテナは MySQL ではないため、準備が完了するまで sleep コマンドを実行します。
          name: MySQL が準備できるまで待機
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run: mv src/* .
      - restore_cache:
          key: mod-{{ checksum "go.sum" }}

      - run: go get -v -t -d ./...
      - run: go test -v ./...

      - save_cache:
                key: mod-{{ checksum "go.sum" }}
                paths:
                  - $GOPATH/pkg/mod
