server :
  port : "1323"
  mock : false

# mysql
database :
  host : "localhost"
  port : "3306"
  user : "kazuya"
  password : "kazuya"
  database : "power-phrase2"

jwt :
  secret : power-phrase-secret
